CS50x/final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("finance.urls"))
]

CS50x/final_project/finance/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login_view"),
    path("register/", views.register, name="register"), 
    path("logout/", views.logout_view, name="logout_view"),
    path("create/", views.create, name="create"),
    path("profile/<str:user_username>", views.profile, name="profile"),
    path("post/<str:post_id>", views.post_page, name="post_page"),
    path("create_professional/", views.create_professional, name="create_professional"),
    path("categories/", views.categories, name="categories"),
    path("category/<str:post_category>", views.category, name="category"),
    path("profile/<str:username>/professional", views.professional_profile, name="professional_profile"),
    path("search/subject", views.search_subject, name="search_subject"),
    path("search/content", views.search_content, name="search_content"),
    path("saved/post/detail/all", views.saved_post_all_detail, name="all_saved_post"),
    path("saved/post/detail/<str:post_id>", views.saved_post_id, name="saved_post"),
    path("detail/save/post/<str:post_id>", views.save_post_detail, name="save_post"),
    path("saved/user/<str:user_username>", views.view_saved_posts, name="view_saved_posts"),
    path("detail/like/post/<str:post_id>", views.detail_like_post, name="detail_like_post"),
    path("save/like/<str:post_id>", views.like_function, name="like_function"),
    path("detail/comment/like/post/<str:comment_id>", views.detail_like_comment, name="detail_like_comment"),
    path("save/comment/like/<str:comment_id>", views.add_like_comment, name="add_like_comment"),
    path("save/edit/post/<str:post_id>", views.edit_post, name="edit_post"),
    path("save/edit/comment/<str:comment_id>", views.edit_comment, name="edit_comment"),
    path("profile/<str:username>/professional/add/opinion", views.add_opinion, name="add_opinion")
]

CS50x/final_project/finance/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db.models.signals import post_save, post_delete, pre_save
from django.dispatch import receiver


# Creating a SQL table for profile along with information about whether it is a professional profile (automatically becomes a professional profile upon creation)
class User(AbstractUser):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=128)
    if_professional = models.BooleanField(default=False)
    
    def __str__(self):
        return f"ID: {self.id}, User: {self.username}, e-mail: {self.email}, password: {self.password}, if professional: {self.if_professional}"

# SQL table for posts
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="POST")
    temat = models.CharField(max_length=500)
    post = models.CharField(max_length=10000)
    timestamp = models.DateTimeField(default=timezone.now)

    CATEGORY_CHOICES = [ 
        ('zakladanie_firmy', 'Company Formation'),
        ('finance_inwestycje', 'Finance and Investments'),
        ('marketing_sprzedaz', 'Marketing and Sales'),
        ('zarządzanie_operacje', 'Management and Operations'),
        ('prawo_regulacje', 'Law and Regulations'),
        ('rozwoj_osobisty', 'Personal Development and Networking'),
        ('inne', 'Others')
    ]
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='inne')
    like_count = models.IntegerField(default=0)

    def __str__(self):
        return f"ID: {self.id}, User: {self.user.username}, temat: {self.temat} post: {self.post}, timestamp: {self.timestamp}, category:{self.category}, likes:{self.like_count} "
    
# Database for comments
class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comment")
    comment = models.CharField(max_length=3000)
    timestamp = models.DateTimeField(default=timezone.now)
    like_count = models.IntegerField(default=0)

    def __str__(self):
        return f"ID: {self.id}, User: {self.user.username}, post: {self.post.id}, comment: {self.comment}, likes:{self.like_count}, timestamp: {self.timestamp}"

# SQL table for professional users
class ProfessionalUser(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="professional_profile")
    company_name = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length= 255)
    specialization = models.CharField(max_length=255)
    description = models.TextField()
    hourly_rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    availability = models.CharField(max_length=255)
    email = models.EmailField()
    website = models.URLField(blank = True)
    social_media = models.URLField(blank=True)
    years_of_experience = models.IntegerField(blank=True, null=True)
    certifications = models.TextField(blank=True)

    def __str__(self):
        return f"ID: {self.id}, User: {self.user.username}, Specialization: {self.specialization}, City: {self.city}"
    
# SQL table for post likes
class Like(models.Model):
    id = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post_like")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name = "post_like")
    if_like = models.BooleanField(default=True)
    
    def __str__(self):
        return f"ID: {self.id}, User: {self.user.username}, Post: {self.post.id}, if like: {self.if_like}"
    
# Logic for counting likes under posts
@receiver(pre_save, sender = Like)
def before_like_save(sender, instance, **kwargs):
    if instance.pk:
        old_instance = Like.objects.get(pk=instance.pk)
        if old_instance.if_like != instance.if_like:
            if instance.if_like:
                instance.post.like_count += 1
            else:
                instance.post.like_count -= 1
            instance.post.save()

# Logic for updating like 
@receiver(post_save, sender=Like)
def update_like_count_on_save(sender, instance, created, **kwargs): 
    if created: 
        instance.post.like_count = instance.post.post_like.filter(if_like=True).count()
        instance.post.save()

# Logic for updating like after delete
@receiver(post_delete, sender=Like)
def update_like_count_on_delete(sender, instance, **kwargs):
    instance.post.like_count = instance.post.post_like.filter(if_like=True).count()
    instance.post.save()

# SQL table for likes under comments
class Like_Comment(models.Model):
    id = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="like_comment")
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="likes")
    if_like = models.BooleanField(default=True)

    def __str__(self):
        return f"ID: {self.id}, User: {self.user.username}, Comment {self.comment.id}, if like: {self.if_like}"


# Logic for counting likes under comments 
@receiver(pre_save, sender= Like_Comment)
def before_comment_like_save(sender, instance, **kwargs):
    if instance.pk:
        old_instance = Like_Comment.objects.get(pk=instance.pk)
        if old_instance.if_like != instance.if_like:
            if instance.if_like:
                instance.comment.like_count +=1 
            else:
                instance.comment.like_count -= 1
            instance.comment.save()

@receiver(post_save, sender=Like_Comment)
def update_comment_like_count_on_save(sender, instance, created, **kwargs):
    if created:
        instance.comment.like_count = instance.comment.likes.filter(if_like=True).count()
        instance.comment.save()

@receiver(post_delete, sender=Like_Comment)
def update_comment_like_count_on_delete(sender, instance, **kwargs):
    instance.comment.like_count = instance.comment.likes.filter(if_like=True).count()
    instance.comment.save()

# SQL table for saving posts
class Save_Post(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name="save_post")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="save_post")
    if_save = models.BooleanField(default=True)

    def __str__(self):
        return f"ID:{self.id}, User:{self.user.username}, Post: {self.post.id}, If Save: {self.if_save}"
    
# SQL table for rating professional users
class Rating_User(models.Model):
    id = models.AutoField(primary_key=True)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="give_rate_professional")
    professional_user = models.ForeignKey(ProfessionalUser, on_delete = models.CASCADE, related_name="give_rate_professional")
    value = models.PositiveSmallIntegerField()
    opinion = models.CharField(max_length=1000)
    if_used = models.BooleanField(default=False)

    def __str__(self):
        return f"ID: {self.id}, Reviewer: {self.reviewer.username}, Professional: {self.professional_user.user.username}, value: {self.value}, opinion: {self.opinion}, If used: {self.if_used}"

CS50x/final_project/finance/templates/finance/add_opinion.html
{% extends 'finance/layout.html' %}


{% block body %}
<div class="container mt-4">
    <h1 class="text-center">Adding Opinion</h1>
    
    {% if message %}
        <div class="alert alert-success text-center">
            <h2>{{ message }}</h2>
        </div>
    {% endif %}
    
    {% if opinion %}
        <div class="opinion-section">
            <h3 class="text-center">Your opinion about this user:</h3>
            {% for blog in opinion %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Rating: {{ blog.value }} / 5</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Reviewer: {{ blog.reviewer.username }}</h6>
                        <p class="card-text">{{ blog.opinion }}</p>
                        {% if blog.if_used %}
                            <p class="text-success">This service was used</p>
                        {% else %}
                            <p class="text-danger">This service was not used</p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <form method="POST" class="opinion-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="value">Value:</label>
                <div class="star-rating">
                    <input type="radio" id="star5" name="value" value="5"><label for="star5" title="5 stars">&#9733;</label>
                    <input type="radio" id="star4" name="value" value="4"><label for="star4" title="4 stars">&#9733;</label>
                    <input type="radio" id="star3" name="value" value="3"><label for="star3" title="3 stars">&#9733;</label>
                    <input type="radio" id="star2" name="value" value="2"><label for="star2" title="2 stars">&#9733;</label>
                    <input type="radio" id="star1" name="value" value="1"><label for="star1" title="1 star">&#9733;</label>
                </div>
            </div>
            <div class="form-group">
                <label for="opinion">Opinion:</label>
                <textarea id="opinion" name="opinion" class="form-control" maxlength="1000" rows="4"></textarea>
            </div>
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="if_used" name="if_used">
                <label class="form-check-label" for="if_used">If Used</label>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
        </form>
    {% endif %}
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/categories.html
{% extends 'finance/layout.html' %}

{% block body %}
<div class="container mt-4">
    <h1 class="text-center">Categories</h1>
    <hr>
    <div class="categories-list">
        {% for code, name in categories.items %}
            <div class="category-item mb-3">
                <a href="{% url 'category' post_category=code %}" class="btn btn-primary btn-block">{{ name }}</a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

CS50x/final_project/finance/templates/finance/create.html
{% extends "finance/layout.html" %}

{% block body %}
<div class="container mt-4">
    <h1 class="text-center">Create New Article</h1>
    <hr>
    {% if message %}
        <div class="alert alert-success text-center">{{ message }}</div>
    {% endif %}
    <form action="{% url 'create' %}" method="POST" class="create-post-form mt-4">
        {% csrf_token %}
        <div class="form-group">
            <label for="subject">Subject:</label>
            <input type="text" id="subject" name="subject" class="form-control" placeholder="Subject" required>
        </div>
        <div class="form-group">
            <label for="content">Content:</label>
            <textarea id="content" name="content" class="form-control" placeholder="Content" rows="5" required></textarea>
        </div>
        <div class="form-group">
            <label for="category">Category:</label>
            <select id="category" name="category" class="form-control" required>
                {% for code, name in categories.items %}
                    <option value="{{code}}">{{name}}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Add Post</button>
    </form>
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/create_professional.html
{% extends "finance/layout.html" %}

{% block body %}
<div class="container mt-4">
    <h1 class="text-center">Create Your Professional Profile</h1>
    <form action="{% url 'create_professional' %}" method="post" class="professional-form mt-4">
        {% csrf_token %}
        
        <h2 class="form-section-title">Basic Information</h2>
        <div class="form-group">
            <label for="companyName">Company Name <span>(optional)</span>:</label>
            <input type="text" id="companyName" name="companyName" class="form-control">
        </div>

        <div class="form-group">
            <label for="city">City <span>(required)</span>:</label>
            <input type="text" id="city" name="city" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="specialization">Specialization <span>(required)</span>:</label>
            <input type="text" id="specialization" name="specialization" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="description">Description <span>(required)</span>:</label>
            <textarea id="description" name="description" rows="4" class="form-control" required></textarea>
        </div>

        <div class="form-group">
            <label for="hourlyRate">Hourly Rate <span>(required)</span>:</label>
            <input type="number" id="hourlyRate" name="hourlyRate" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="availability">Availability <span>(required)</span>:</label>
            <input type="text" id="availability" name="availability" class="form-control" required>
        </div>

        <h2 class="form-section-title">Contact Details</h2>
        <div class="form-group">
            <label for="email">Email Address <span>(required)</span>:</label>
            <input type="email" id="email" name="email" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="website">Website <span>(optional)</span>:</label>
            <input type="url" id="website" name="website" class="form-control">
        </div>

        <div class="form-group">
            <label for="socialMedia">Social Media <span>(optional)</span>:</label>
            <input type="url" id="socialMedia" name="socialMedia" class="form-control">
        </div>

        <h2 class="form-section-title">Experience and Qualifications</h2>
        <div class="form-group">
            <label for="experience">Years of Experience <span>(required)</span>:</label>
            <input type="number" id="experience" name="experience" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="certifications">Certificates and Courses <span>(optional)</span>:</label>
            <textarea id="certifications" name="certifications" rows="4" class="form-control"></textarea>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Save</button>
    </form>
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/index.html
{% extends "finance/layout.html" %}

{% block body %}
<div class="container mt-4">
    <h1 class="text-center">Welcome to the Finance Forum</h1>
    <form method="get" action="{% url 'search_subject' %}" class="search-form my-4 d-flex justify-content-center">
        <input type="text" name="q" class="form-control search-input" placeholder="Search in Subject">
        <button type="submit" class="btn btn-primary search-button">Search</button>
    </form>
    <form method="get" action="{% url 'search_content' %}" class="search-form mb-4 d-flex justify-content-center">
        <input type="text" name="q" class="form-control search-input" placeholder="Search in Content">
        <button type="submit" class="btn btn-primary search-button">Search</button>
    </form>

    {% if posts %}
        <div class="posts-list">
            {% for post in posts %}
                <div class="post p-4 mb-4 border rounded shadow-sm">
                    <h2><a href="{% url 'post_page' post.id %}" class="post-title">{{ post.temat }}</a></h2>
                    <p>By <a href="{% url 'profile' post.user.username %}" class="post-author">{{ post.user.username }}</a></p>
                    <p>Category: <span class="post-category"><a href="{% url 'category' post_category=post.category %}">{{ post.get_category_display }}</a></span></p>
                    <p><i class="fas fa-thumbs-up"></i> Likes: <span class="post-likes">{{ post.like_count }}</span></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No posts available.</p>
    {% endif %}
    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Finance{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'finance/styles.css' %}" rel="stylesheet">
        <script src="{% static 'finance/front.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    </head>
    <body>
        <div class="navbar">
            <span><a href="{% url 'index' %}">Home</a></span>
            <span><a href="{% url 'categories' %}">Categories</a></span>
            {% if user.is_authenticated %}
                <span><a href="{% url 'profile' user.username %}" id="user_name">{{ user.username }}</a></span>
                <span><a href="{% url 'view_saved_posts' user.username %}">Saved</a></span>
                <span><a href="{% url 'logout_view' %}" id="logout">Logout</a></span>
                <span><a href="{% url 'create' %}">Create New Article</a></span>
            {% else %}
                <span><a href="{% url 'login_view' %}">Log in</a></span>
                <span><a href="{% url 'register' %}">Register</a></span>
            {% endif %}
        </div>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

CS50x/final_project/finance/templates/finance/login.html
{% extends "finance/layout.html" %}

{% block body %}
<div class="container mt-5">
    {% if message %}
        <div class="alert alert-warning text-center" role="alert">
            {{ message }}
        </div>
    {% endif %}

    <h1 class="text-center mb-4">Login</h1>
    <form action="{% url 'login_view' %}" method="POST" class="login-form mt-4 needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
            <div class="invalid-feedback">
                Please enter your username.
            </div>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
            <div class="invalid-feedback">
                Please enter your password.
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Login</button>
    </form>
    <p class="text-center mt-3">Don't have an account yet? <a href="{% url 'register' %}">Register here.</a></p>
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/post_category.html
{% extends 'finance/layout.html' %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Posts in This Category</h1>
    {% if posts %}
        <div class="posts-list">
            {% for post in posts %}
                <div class="post p-4 mb-4 border rounded shadow-sm">
                    <h2><a href="{% url 'post_page' post.id %}" class="post-title">{{ post.temat }}</a></h2>
                    <p>By <a href="{% url 'profile' post.user.username %}" class="post-author">{{ post.user.username }}</a></p>
                    <p>Category: <span class="post-category">{{ post.get_category_display }}</span></p>
                    <p><i class="fas fa-thumbs-up"></i> Likes: <span class="post-likes">{{ post.like_count }}</span></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-center">No posts available in this category.</p>
    {% endif %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/profile.html
{% extends "finance/layout.html" %}

{% block body %}
<div class="container mt-5">
    {% if user_exist == True %}
        <h2 class="text-center mb-4">Welcome to {{ username }}'s profile</h2>
        {% if user.username == username %}
            <div class="text-center mb-3">
                {% if profile_user.if_professional == False %}
                    <a href="{% url 'create_professional' %}" class="btn btn-primary">Upgrade to Professional</a>
                {% else %}
                    <a href="{% url 'professional_profile' username=username %}" class="btn btn-primary">Go to Your Professional Website</a>
                {% endif %}
            </div>
        {% else %}
            {% if profile_user.if_professional == True %}
                <div class="text-center mb-3">
                    <a href="{% url 'professional_profile' username=username %}" class="btn btn-primary">Go to Professional Website</a>
                </div>
            {% endif %}
        {% endif %}
    {% else %}
        <h2 class="text-center">This user does not exist yet</h2>
    {% endif %}
    <hr>
    <div class="posts-list">
        {% if posts %}
            {% for post in posts %}
                <div class="post p-4 mb-4 border rounded shadow-sm bg-light">
                    <h2><a href="{% url 'post_page' post.id %}" class="post-title">{{ post.temat }}</a></h2>
                    <p>By <a href="{% url 'profile' post.user.username %}" class="post-author">{{ post.user.username }}</a></p>
                    <p>Category: <span class="post-category"><a href="{% url 'category' post_category=post.category %}">{{ post.get_category_display }}</a></span></p>
                    <p>Likes: <span class="post-likes">{{ post.like_count }}</span></p>
                </div>
                <hr>
            {% endfor %}
        {% else %}
            <p class="text-center">This user has not published any posts</p>
        {% endif %}
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/saved.html
{% extends "finance/layout.html" %}

{% block body %}
<div class="saved-posts container mt-5">
    <h2 class="text-center mb-4">Saved Posts for {{ user.username }}</h2>
    {% if posts %}
        <div class="posts-list">
            {% for post in posts %}
                <div class="post p-4 mb-4 border rounded shadow-sm bg-light">
                    <h2><a href="{% url 'post_page' post.id %}" class="post-title">{{ post.temat }}</a></h2>
                    <p>By <a href="{% url 'profile' post.user.username %}" class="post-author">{{ post.user.username }}</a></p>
                    <p>Category: <span class="post-category"><a href="{% url 'category' post_category=post.category %}">{{ post.get_category_display }}</a></span></p>
                    <p>Likes: <span class="post-likes">{{ post.like_count }}</span></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-center">You have not saved any posts yet.</p>
    {% endif %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

CS50x/final_project/finance/templates/finance/search.html
{% extends 'finance/layout.html' %}

{% block body %}
<div class="search-results container mt-5">
    <h2 class="text-center mb-4">Search Results</h2>
    <p class="text-center"><strong>Query:</strong> {{ query }}</p>
    {% if posts %}
        <div class="posts-list">
            {% for post in posts %}
                <div class="post p-4 mb-4 border rounded shadow-sm bg-light">
                    <h2><a href="{% url 'post_page' post.id %}" class="post-title">{{ post.temat }}</a></h2>
                    <p>By <a href="{% url 'profile' post.user.username %}" class="post-author">{{ post.user.username }}</a></p>
                    <p>Category: <span class="post-category"><a href="{% url 'category' post_category=post.category %}">{{ post.get_category_display }}</a></span></p>
                    <p>Likes: <span class="post-likes">{{ post.like_count }}</span></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-center">No posts found. <a href="{% url 'create' %}">Create a new article here</a></p>
    {% endif %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}